### ISSUE TITLE
Unboxing feature proposition 

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#1003]
I think we should have something like smart unboxing functionality (python like)

Case 1
```Livescript
a, b, c = [1 to 10]

console.log a,b,c # => 1,2,3
```

Case 2
```Livescript
a, b, c = { a: 1, b: 2, c: 3 }

console.log a,b,c # => 1,2,3
```

Implementation
```Livescript
unbox = (o, varName, index)->
   | typeof! o is \Object => o[varName]
   | typeof! o is \Array => o[index]
   | index is 0 => o
   | _ => null
```

**Comment by rhendric** [comment]
I don't think this is a good idea because of `foo a, b = x`, which already compiles to `foo(a, b = x)` and not `foo(unbox(x, 'a', 0), unbox(x, 'b', 1))`. Having `a, b = x` mean unboxing and `foo a, b = x` mean simple assignment would be pretty unintuitive.

**Comment by askucher** [comment]
Why you put `foo` there? it is not allowed. 

First of all please learn python and try to use it in math formulas before your decision.

**Comment by rhendric** [comment]
If you would try `foo a, b = x` in a LiveScript compiler, you will find that it is indeed allowed, so I'm not sure what it is you're trying to say.

And I assure you I'm experienced with Python. My decision has nothing to do with Python, though; at risk of insulting you by stating the obvious, Python supports a different syntax than LiveScript, and you made a proposal for LiveScript, so I have to judge it based on what does and doesn't work in LiveScript.

**Comment by askucher** [comment]
I cannot find any sense in your arguments. I proposed to use python to show how simple it is and intuitive. The concern is your "would be pretty unintuitive." - I think you are not one who can say "intuitive" or "unintuitive" without valuable confirmation.

**Comment by rhendric** [comment]
Okay, let me try to explain in more detail.

First: in LiveScript, `foo a, b = x` is currently valid. It means `foo(a, b = x)`. I don't know whether you would ever write code like that, but it doesn't matter—in LiveScript, people can, and I'm not going to change something you can write in LiveScript to be invalid without a very good reason. So that's the first thing that I would want you to understand—that `foo a, b = x` has a meaning and I don't think it's a good idea for that meaning to change, because I want to avoid breaking existing code. Agree or disagree?

Second: *given* that `foo a, b = x` means what it means, I think there is a *difference* between how that expression works and what you're proposing for `a, b = x` alone on a line. You want `a, b = x` to mean `a = unbox(x, 'a', 0); b = unbox(x, 'b', 1);`, and that is very different from what's happening in `foo a, b = x` => `foo(a, b = x)`. Agree or disagree?

Third: *given* that `foo a, b = x` means what it means, and *given* that there is a difference between how that expression works and how you want `a, b = x` to work, I think there is a *conflict* between those two ideas that programmers would find unintuitive. It may or may not be an actual grammar conflict—in the first case, the `=` binds more tightly than the `,` (if you think about the tree of that expression, it would group something like `(foo a, (b = x))`), but in the second case, the `,` binds more tightly than the `=` (the grouping is like `((a, b) = x)`), and that would ordinarily be a bad sign for a grammar, but perhaps there's a clever way to work around that. I haven't thought too deeply about it, because the *real* objection is that I think that humans looking at `foo a, b = x` would expect the part of that expression that looks like `a, b = x` to behave the same way that `a, b = x` would behave if alone on a line. Most of the time, in a programming language, if you can take a piece of an expression out of a larger expression and still use it on its own, it has at least a similar meaning to its original meaning in the larger expression. (The ‘if’ there is important; I'm not talking about fragments that you can take out of an expression that make no sense on their own.) This is not a universal rule (for example, LiveScript violates this when it makes `{ +flag }` mean `{ flag: true }`, but `+flag` on its own means just what it would mean in JavaScript), but when it's violated, I think people are surprised and have to do some learning. Agree or disagree?

If you agree with all of the above, then you should understand why I think your proposal is unintuitive: because there is an existing kind of expression made of commas and equals signs in LiveScript that means a completely different thing, and people expect things that look similar to be similar. If you disagree, please explain what part of the argument you disagree with.

**Comment by rhendric** [comment]
P.S. In Python, parentheses change the meaning of equals signs within them. So in Python, the equals sign in `foo(a, b=x)` doesn't mean assignment; it means value of named parameter. That's how Python edges around the mental conflict between `a, b = x` and `foo(a, b=x)`: because the equals sign in the former case doesn't appear in parentheses, it means to set the value of some new variables; and since Python programmers already know it means something different, it can have different binding precedence relative to commas as well, because why not? In LiveScript, the equals sign in both cases means regular old assignment. That's why bringing in Python idioms doesn't necessarily work as well in LiveScript, and why pointing at Python and saying that it's intuitive there doesn't convince me that it would be as intuitive in LiveScript.

**Comment by determin1st** [comment]
this works:

[a, b, c] = [1 to 10]
[a, b, c] = arrayVar

{a, b, c} = {a: 1, b: 2, c: 3}
{a, b, c} = objectVar

not much to type..

**Comment by askucher** [comment]
ok. 

`foo a, b = x` means assignment of variable before passing it into the function.
so the real use case that you can use `b` variable right after invoking. 

It is kind of useless thing for me but if you want to support community who thinks it is not useless - okey, I will live with that. 

But 

The use case of `a, b = boxed_object_or_array` much more better use case. You can replace object with array and do not change the code from `{ a, b, c }` to `[a, b, c]`  everywhere where you use it. Of course dynamic language has problems with `search and replace`
Moreover this kind of syntax is closer to math and code looks much clear. 
when in this case `foo a, b = x` code looks confusing. I would say ... why not it means `foo(a, b) = x`

**Comment by vendethiel** [comment]
> foo(a, b) = x

Because that's never valid JS. It does parse, but outside of WScript, I don't know that it's ever been valid JS.

> The use case of a, b = boxed_object_or_array much more better use case.
> You can replace object with array and do not change the code from { a, b, c } to [a, b, c] everywhere where you use it.

Except one has order, and the other one doesn't. If you use `{a, b} = o` and `{b, c} = o` (because you only care about a few properties), everything breaks.

> why not it means foo(a, b) = x

It's worse here, `foo(a, b) = x` used to be a specific syntax in LiveScript to declare curried functions, Haskell-like.

**Comment by rhendric** [comment]
@askucher, when anyone proposes a change to LiveScript, there are two things I have to think about first: does this preserve existing LiveScript code, and does this increase (or at least, not decrease) the internal consistency of the language? On occasion, increasing the consistency of the language will justify to me a minor backward-incompatible change. However, in no case yet, and in no case I can imagine in the future, have I thought/will I think that a change that *decreases* the internal consistency of the language will be worth any amount of convenience. Even in the conversation over at #999, where the potential value is massive, I'm arguing for consistency with existing LiveScript forms.

So *even if* I agreed that `a, b = emcd 1, 2` represented some kind of vast improvement over `[a, b] = emcd 1, 2` (and I don't, to be clear—I think the second, existing syntax is clearer because it is more explicit, it makes lvalues look like the rvalues they destructure, it involves less run-time indirection, and as determin1st notes, it's only two extra characters), the argument that I already laid out to you in detail would prevent me from making this change. If you can't defeat that argument, you can't convince me that this is a good idea *for LiveScript*.

Please note that I'm not asserting that this isn't a good idea *at all*. Although I would not design a language that way, it may be that a language similar to LiveScript but that forbids expressions like `foo a, b = x` and enables expressions like what you're proposing is, in some objective or subjective way, a better language than LiveScript. If you are convinced that is the case, and think that ven and determin1st and I are all fools for not seeing it, my advice is to write that language! I won't make LiveScript into that language because LiveScript already has a user base, and given that LiveScript development comes at an average of one or two new commits a month these days, I'm unwilling to disrupt that user base by changing the core design of LiveScript too much. But your language would start with only you. You can experiment as much as you want. I know, in fact, that you have already forked LiveScript for your own purposes, so I know that this suggestion is not news to you. I bring it up only to contrast between my position, where I am forced to be conservative, and yours, where you are free to implement whatever patterns you find most intuitive, with no constraint other than your own ability to write the implementation.

**Comment by rhendric** [comment]
@Announcement, the difference between those two expressions is not the point. The point is the difference between `foo a, b, c = x` and (proposed) `a, b, c = x`; in the first, the assignment stops at the comma, and in the second, the assignment extends through all the commas. Put another way, if someone gets used to seeing `a, b, c = x` meaning the same thing as `[a, b, c] = x` (ignoring for a moment the proposed complication that this kind of destructuring should apply to both arrays and objects), I anticipate seeing an issue opened asking why `foo a, b, c = x` doesn't translate into `foo(a = x[0], b = x[1], c = x[2])` or something like that, since they are used to the assignment extending leftward through the commas.
