### ISSUE TITLE
Type system for Livescript is realized

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#1048]
Typed functions

Look `=>` is already represented here https://github.com/gkz/LiveScript/issues/1046

`=>` is monadic and type checked. 

```livescript
func = (String str)=>
   <1 "ok #{str}"

err, data <- func "str" # data => "str"
err, data <- func 1 # => err => "function does not exists"
```

Lets make it

```livescript
# functions should be inline 

func = (String str)=>
   console.log str

func = (String str, String str2)=>
   console.log str

func = (Number str)=>
   console.log str

func = ([])=>
   console.log \empty-array

func = ([head, ...tail])=>
   console.log \array

console.log func "str" # => "str"
console.log func 1 # => 1
```
We should have Haskell like pattern matching 

Should be compiled into 

```Javascript

var func = $typed(func__String, 
                        func_String_String, 
                        func_Number, 
                        func_EmptyArray, 
                        func_Array);

$typed = function() {
    ... processing here
}

```

**Comment by rhendric** [comment]
As with several of your recent requests (#1046, #1040, #1003), this syntax already means something else in LiveScript.

It seems like what you're asking for is [function overloading](https://en.wikipedia.org/wiki/Function_overloading), not ‘Haskell like pattern matching’. If you [search on npm](https://www.npmjs.com/search?q=function%20overloading) you can find several packages for this problem. (Package or not, some run-time support is necessary to distinguish if an argument is an instance of `String` or `Number` or some more complex type—this isn't something that could be solved by just compiling down to different JavaScript without inserting code that basically does what those packages do.)

I'm closing this because LiveScript currently has no concept of types. Maybe once it does, some support for overloading (with a different syntax) might make sense.

**Comment by rhendric** [comment]
Go for it! Succeed or fail, I think you'll learn a lot.

(For the record, for anyone [interested in the history](/gkz/LiveScript/graphs/contributors), *I* didn't fork anything. I only started contributing several years after gkz's fork of satyr's Coco, which was the original fork of CoffeeScript.)
