### ISSUE TITLE
Changelog 1.6

### ISSUE THREAD

**Issue by francescoagati** [gkz/LiveScript#1069]
Hi,
There is a changelog for 1.5 and 1.6 versione?

**Comment by vendethiel** [comment]
#997

**Comment by rhendric** [comment]
Yes, though it hasn't been published to livescript.net yet because 1.6.0 hasn't been published to npm yet (only @gkz has the keys to do this). If you're getting the 1.6.0 release from GitHub, you can preview the new changelog (along with the rest of the updated documentation) at https://rawgit.com/gkz/LiveScript/gh-pages-next/.

**Comment by francescoagati** [comment]
Thanks
