### ISSUE TITLE
Awesome bits of syntax you didn't realise worked but are pretty sweet anyway

### ISSUE THREAD

**Issue by quarterto** [gkz/LiveScript#233]
My favourite:
```coffeescript
(a ? throw TypeError "give me an argument!")->
```

**Comment by phanimahesh** [comment]
I can't even parse what you wrote, @vendethiel. Can you please help me deconstruct that horror?

**Comment by vendethiel** [comment]
Certainly.

`^^[]{}@@=>->|..=><[]>+~>%"#@".>>.&*$~_?\`°`

The first part is `^^[]{}@@`
`^^` is "clone", which'll clone whatever comes after.
Then `[]`, a simple empty array. Then a special access, called **semi-autovivification** (it's in the docs!), between `[]` and `@@` (that, is, constructor).
This line is like `[]{}.constructor`.

Then we see `=>`. This creates a cascade, that will be referred to as `..` (`1 => console.log(..)` is `console.log(1)` in disguise). That also means the result will be "discarded":

(`console.log (5 => console.log ..)` print 5 two times, since the cascade return the referee)

And that's where the second part starts `->|..=><[]>+~>%"#@".>>.&*$~_?\\`°`:

The beginning is `->` this is just a function. It's then followed by a "case", `|`.
The first (and only) case is `..` (which refers to the first part, that is, `clone([].constructor ?= {})`.
in this case (the `=>` here is `then`, as with `switch 1 | 1 => console.log yay`).

In this case (which will.. never trigger), we do this: `<[]>+~>%"#@".>>.&*$~_?\\`°`

`<[]>` is an empty literal array. `+` is just a plus. `~>` is a bound function.
`%"#@"` is "unjoined interpolation" (which will probably be removed soon-ish). It returns the part of the strings, partitioned on whether they're an interpolation or not, as an array.

`%"a#{b}c"` returns `["a", b, "c"]`.
