### ISSUE TITLE
`for else` should work ok with `when`

### ISSUE THREAD

**Issue by vendethiel** [gkz/LiveScript#278]
Currently, `for a in [1] when 0 => 1 else throw "Does not happen :(!"`
will *not* throw the exception because `yet$` is assigned `false` with no regards to `when`'s cond. I think it should be wrapped too. thoughts?

**Comment by vendethiel** [comment]
I'll go ahead and label this as a bug.

**Comment by pepkin88** [comment]
Bump for opinions.

I agree that `yet$ = false;` should be inside the `if` block from the guard. Now `when` behaves just like an ordinary `if`. With the change, using `for..when..else` gets more practical, the old behavior could be achieved using an `if`.

But I think your code @vendethiel is not a good example of that, because it already doesn't throw. The behavior might already have changed, but judging from the rest of your post, I think it has not.

**Comment by vendethiel** [comment]
> But I think your code @vendethiel is not a good example of that, because it already doesn't throw.

My point is that: it *should* throw. The loop hasn't run at all.

**Comment by pepkin88** [comment]
OK, I see. The sentence "Currently, _(the code)_ will throw the exception..." threw me off guard.

**Comment by vendethiel** [comment]
Oh wow! That one has been there for a while. I’ll fix it, ty.

**Comment by vendethiel** [comment]
Actually re-reading this makes me very confused: was my english that bad, did the behavior change, or is the « should not happen » actually « should happen »
