### ISSUE TITLE
Inconsistent comprehension syntax

### ISSUE THREAD

**Issue by texastoland** [gkz/LiveScript#286]
Every loop is structured with some variation of `for in` or `for of`. Doing it this way keeps us from being able to `[f .. for of obj]` even forgetting about object comprehensions. I see that as a separate bug. The other point of inconsistency was `it` in lambdas. Cascades are nicer for property access and appear in both `with` and comprehensions.

**Comment by vendethiel** [comment]
@gkz ?

**Comment by AppShipIt** [comment]
This and `!` were my biggest complaints. I've since moved on to ES2016.

**Comment by vendethiel** [comment]
I'm gonna try one last time... @gkz?

**Comment by AppShipIt** [comment]
Sorry I closed it because of lack of support. I thought inconsistencies (this issue, `!` operators, ambiguous implicit lists, function application associativity, etc.) would be addressed by LS2 but never culminated. With `do` expressions in ES2016 making `switch` more functional along with many features adopted from Coffee I think the community will be best served by building on Babel. I'm starting working on a partial application symbol and currying prototype methods inspired by LS.

**Comment by vendethiel** [comment]
That's okay, I understand. I still believe LS to be a better option and this issue should have a conclusion, though :). (I'm very biased)

**Comment by gkz** [comment]
So, you want to add '[f .. for of obj]'? 

Please keep issues open even if you are no longer interested as they might be revisited in the future.

**Comment by vendethiel** [comment]
Basically, yes. I guess we could allow `for in obj` for consistency (the in would thus be optional)

**Comment by AppShipIt** [comment]
And `it` would be cascade for consistency as well.

**Comment by vendethiel** [comment]
That's something I disagree with, and if it needs to change, I'd rather see it the other way around... But I'd be against such a breaking change for LS 1.x anyway...
