### ISSUE TITLE
Array conversion

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#373]
FIRST

``` Livescript
table1 =
  * id: 1
```

converts to (Single object)

``` Javascript
var table1;
table1 = {
  id: 1
};
```

SECOND

``` Livescript
table1 =
  * id: 1
  * id: 2
```

converts to  (Array!)

``` Javascript
var table1;
table1 = [
  {
    id: 1
  }, {
    id: 2
  }
];
```

I cannot find logic why it is so. I did a bug. How I can create array with 1 item

**Comment by chrisvfritz** [comment]
Just for the record, this "feature" is the first major gotcha I've found in LiveScript. When a behavior is useful in one niche case, but also creates difficult-to-diagnose bugs in *every other case*, it should not exist IMO. In LiveScript horror stories, I have a feeling "single-item arrays" will become a recurring character.

**Comment by chrisvfritz** [comment]
I'm going to argue for reopening this. The definition of a bug is behavior that is incorrect or unexpected. This is clearly unexpected. There's already a way to define an object, so when I add that little asterisk, I'm communicating my intent that **this should be an object inside of an array**. Instead of the result I expect, I have to add a few dots to tell the compiler, "But seriously. This should really be an array." That's a bug.

The behavior isn't even consistent with other ways of declaring an array. This *does* give me what I expect:

``` livescript
table = [
  id: 1
]
```

If it were actually a good thing to not define an array when explicitly defining an array, this behavior would be universal. Please, *please* consider changing it.

**Comment by gkz** [comment]
I would change this in a backward-incompatible version

**Comment by chrisvfritz** [comment]
:+1: :smiley:
