### ISSUE TITLE
Partial application should be bound (like bound functions)

### ISSUE THREAD

**Issue by isiahmeadows** [gkz/LiveScript#634]
It's really confusing to have code like this constantly throw TypeErrors:

```ls
class Walker
    (@visitors) ->

    walkList: (list) !->
        list
        |> filter (.type of @visitors)
        |> each @walk

    # more methods
```

The problem is this partial function:

```ls
(.type of @visitors)
```

It looks like it should be bound to the current instance, equivalent to this code:

```ls
(node) ~> node.type of @visitors  # bound
```

It's really equivalent to this, which was a rather unexpected gotcha:

```ls
(node) -> node.type of @visitors  # not bound
```

This gotcha is a little misleading. It feels like a small fix, but I don't know a lot about the internal compiler structure.

**Comment by summivox** [comment]
Okay. After writing a patch that implements this behavior, I realized that it might not always be what you expect. Consider this:
```livescript
o = a: 1, f: (@a =)
```
Here unbound `this` is intended.

My feelings:

* A bound `this` feels "right" and might be more common \[citation needed\], since these implicit functions are **intended** for writing quick inline lambdas (where you would assume bound `this`), not methods
* Syntax to support both bound and unbound might be overkill? Crazy idea: pick another sigil for bound `this`
