### ISSUE TITLE
Warn when shadowing outer variable

### ISSUE THREAD

**Issue by Diggsey** [gkz/LiveScript#677]
This is one of the few "features" of livescript which repeatedly catches me out, and as bugs go, it's particularly difficult to track down.

Essentially, there are two possible intentions when assigning to a variable:
1) Declare a new, fresh variable shadowing any outer variable
2) Modify an outer variable

Javascript will default to (2), whereas Livescript will default to (1). However, IMO it would save a lot of time, and result in much more stable code, if Livescript additionally emitted a warning in the ambiguous case.

This would introduce the need for explicit shadowing, which could be done using the "let" keyword.

Obviously it's not possible to detect shadowing of variables from the global scope which were declared in a different file. However, I think this is acceptable, as it's significantly less likely that option (2) is the desired behaviour in that situation, and so warning about it is unnecessary.

**Comment by vendethiel** [comment]
I think I'd like "the opposite" actually, having to predeclare all variables a block will use (either by a smalltalk-like block or simple "var"s) and always have to use ":=" to reassign, even from the same scope.

**Comment by jampekka** [comment]
Please don't warn about this, at least by default. There are many cases where thing like this is validly used (eg reusing loop variable names) with intentional shadowing. This is exactly the madness why I (luckily) found livescript after the coffeescript scoping insanity.

I think in general assigning to outer scope should always be such an exceptional case that a programmer should notice it. In fact this is quite a code smell, but admittedly often required in JS callback soup etc.

**Comment by gkz** [comment]
I don't think warning is necessary, as it is actually desired sometimes (thus our different compilation than CoffeeScript)
