### ISSUE TITLE
->* not return last code line by default

### ISSUE THREAD

**Issue by darrrk** [gkz/LiveScript#696]
```coffeescript    
->*
  "not returned"
```

```javascript
// Generated by LiveScript 1.3.1
(function*(){
  "not returned";
});
```

**Comment by darrrk** [comment]
`~>` similary

**Comment by vendethiel** [comment]
That's by design.

**Comment by darrrk** [comment]
But this causes logical inconsistence with simple `->`, `~>` functions
Also this behavior conflicts with `co` library, where returned value in generator function resolve promise
I think more right `!->*`, `!~>*` need for this behavior

**Comment by unclechu** [comment]
Agreed with @darrrk, it looks little illogical. I hope it will be changed in next major release.

**Comment by gkz** [comment]
I'm not aware of the use-cases for returning from generators (enough so that we make it automatic). Could someone please post describing them?

**Comment by khoerling** [comment]
@gkz check out TJ's co API:
https://github.com/tj/co

**Comment by darrrk** [comment]
Also CoffeeScript returns from generator too.

**Comment by raine** [comment]
I've used `return` inside generators that are recursive so that you can get the final value out, and sometimes I've needed it get promises work properly. e.g. if I hadn't returned explicitly, the parent would not have waited for the coroutine to complete when issuing `then`, or something like that.

Some examples: [1](https://github.com/raine/ez-jenkins/blob/14dc1e5c3fed78e6ecbfba49b03c8f230f4e097c/src/api/tail-build.ls#L61-L70) [2](https://github.com/raine/ez-jenkins/blob/c68948b0d0b6f21586cb568ac56a57153fd12257/src/cli/configure.ls#L10-L20)

**Comment by gkz** [comment]
OK, well unless someone can think of an example of how automatic returning from generators will screw things up, I think we should turn on the feature in the next version of LS

**Comment by unclechu** [comment]
@gkz Very sorry about off-topic (can't find the issue, I'm sure I seen it earlier), but nested generators will be cool too.
```livescript
*<- co
yield some-promise
```
And with arguments
```livescript
(arg) *<- co.wrap
yield some-promise arg
```

**Comment by blvz** [comment]
@unclechu #670
