### ISSUE TITLE
Require/import variables to current local scope

### ISSUE THREAD

**Issue by jampekka** [gkz/LiveScript#700]
Especially with "utility libraries" like `prelude-ls` or `ramda` it's quite tedious to prefix/splat the used functions every time, and having them in a global scope isn't very nice either. This tediousness probably leads people to write less modular stuff they otherwise would.

In fact, "injecting" the names to local scope is already possible with:

    for name, val of require 'somelibrary' then eval "var #name = val"

but this isn't very pretty.

An import syntax could be extended to "contain" this hack. Eg the `import` / `<<` operators without lhs-operand could dump these as local variables, or `{...} = require 'somelibrary'` could be quite intuitive too.

PS. Please no knee-jerk "eval is bad" responses. Valid arguments and critique very welcome however.

**Comment by vendethiel** [comment]
No thanks, eval is bad.

**Comment by jampekka** [comment]
What's really terrible is the attitude of collaborators in this bugtracker. Forkyforky time closing in.

**Comment by gkz** [comment]
I think supporting the ES6 import syntax is a future goal, however I don't think it fits your use-case

**Comment by gkz** [comment]
Also I would like to mention that I don't mind feature requests, even if they are not what we are interested in doing, because it is nice to see people be engaged and interested in the project - so by all means, keep it coming!

**Comment by jampekka** [comment]
I would too like to see more people getting engaged in LiveScript and I really like how it's experimenting with different ideas, some which are most likely knee-jerkly dismissed in other projects. That's why I'm especially surprised by the attitude towards feature requests, or even fully valid bug reports . This sort of thing is probably a big reason why people are moving to LS from CoffeeScript.

I understand that using eval for this is not optimal, but it's a trade off, as everything is. And I think this is a very common real-world use case. Currently people are probably dumping such libraries into the global scope, which I think is a worse trade-off, and not much better for static analysis.

The eval-hack is also only one way to implement this, and by no means I'm meaning that it should be default behavior or even encouraged. It could be also implemented with `with`, although I don't see any advantages in it and it would cause an extra (JS) scope.

One possibility would be to statically scan the imported module for the names during compilation, which would allow lexical analysis. Implementing such stuff may be out of scope for LS, but it would help real-world usage a lot.

I understand if LS doesn't want to make such trade-offs, but I would like a bit less arrogant responses to feature requests and bug reports.

**Comment by vendethiel** [comment]
I love feature requests as well. I really do. The issue is - everyone wants their per feature, or something that's impossible as a whole in LS' current state (macros, or worse, user-defined operators, etc) **and** something that doesn't fit the rest of the feature set of the language **and** is implemented as hack (which we have enough of already).

I mentioned the reasons earlier, and listed a few more: this is really just "with(){}" without he indentation, is not future-proof at all (imagine a library adds another export, maybe your code will break in mysterous way, etc), is going in th opposite direction of ES6 modules (which offer *more* static analysis possibilities), and really, is implemented as a hack that will make your code a lot slower, a lot harder for other people to come around and read (if I see a function used, I **cannot** guess which library imported it). There's also a solution I mentioned on IRC to do what you want (`<- -> it(Object.create null`), that doesn't need to add any kind of feature and that can rely on `import` and such.

This particular feature requests goes in the oppposite direction that LS "wants" to take with LS2, breaks a lot of programmers' basic tools, and also is pretty much impossible in LS because we **need** to know which variables are in our scope for certain operations (`?=`, `:=`, etc)

**Comment by vendethiel** [comment]
> One possibility would be to statically scan the imported module for the names during compilation, which would allow lexical analysis. Implementing such stuff may be out of scope for LS, but it would help real-world usage a lot.

This is something a lot of "js bundlers" have tried to do (like browserify), and as far as I know, it's always been a pain.

> The eval-hack is also only one way to implement this, and by no means I'm meaning that it should be default behavior or even encouraged. It could be also implemented with with, although I don't see any advantages in it and it would cause an extra (JS) scope.

I'm not even saying "with" is better than "eval". I'm just saying that the construct you're asking for exists in JS, was refused for coffee/etc, and from which everyone in the js community has been running away off as well

> but I would like a bit less arrogant responses to feature requests and bug reports

First off: I'm sorry. This was definitely not supposed to sound arrogant. That's why I dropped on IRC to discuss the specifics of this feature, and how it could work considering our current state/the state we want to be "next".
Everyone has great and really interesting ideas here, but as I've said before, I think they collide too much with everything else. I asked you how it could work then, and got the answer that "our tools should work like fuzzy matchers, unit tests, explicit types (etc) are fake friends". I happen to strongly disagree with this, but the point where it breaks down is that -- none of our tools work like that "yet". You suggested a few more ideas (before on irc), like dynamically scoped variables as function arguments. I have no idea if this could be made sane with completly new tools going with this idea, but considering our current "state of the art" on these tools (compilers included), that seems hard to me.

So, in the end,  I'll sum up with this: I'll leave these issues (that I consider "inherently" flawed, as in, flawed-by-design, for the angle I'm coming from) opened, and maybe someone will have an even better idea on how it can be made to work in the language. Because I definitely love feature requests as well, even if I consider LS a bit bloated and having a tad too many... "Write-only features"

But I just don't see how this one can make it, as it breaks thee compiler in ways most other tools failed to fix (we don't want `{...} =` to create globals, for example)w

**Comment by rightfold** [comment]
The main problem I have with this isn't `eval`. It's that the feature instantly makes all code using it unreadable. See your average C, Haskell and Ruby code.

**Comment by jampekka** [comment]
How about the average Python code? Python has `from module import *`, but it is rarely used exactly because of the unreadability. However, there are cases where this is very useful. Actually it's so useful, that lsc has a flag to dump the prelude-ls exports into the global namespace, which I think may well be even uglier hack than a few evals.

And I think the lack of such construct actually leads people to avoid writing modular stuff. For example I have a small library where I specify math operations that work with vectors (oh to have operator overloading) and I like to separate logically different stuff into separate files. So without this I'll have to start almost every file with the boilerplate of

    {sub, add, mul, div, pow, norm} = require './vmath.ls'

And as AFAIU Livescript is all about reducing boilerplate, and that's why I'm using it, this is very annoying. I don't really see how this is much more "unreadable" than having `+ - * **` etc appearing `out of nowhere`.

Anyway, I think it should be the editor's role to point out where an identifier comes from. The computer can easily find that out without the need of manual code noise. But this is also a valid argument against the `eval` implementation.

Every feature can be abused, but I don't think that should be the (sole) reason for not having a feature. And to repeat: nobody would force anybody to use this, ever. It's not meant to replace the current "explicit" stuff.

**Comment by vendethiel** [comment]
Also, https://github.com/jashkenas/coffeescript/issues/292
