### ISSUE TITLE
Dot "static" generates array accessor???

### ISSUE THREAD

**Issue by drozzy** [gkz/LiveScript#722]
Have this really weird bug with LiveScript (tested with 1.3.1 and earlier)

If I have something like this:

    foo.static

The livescript compiler generates:

    // Generated by LiveScript 1.3.1
    (function(){
      foo['static'];
    }).call(this);

Needless to say, this messes with some code in nodejs/express combo... i.e.:

    app.use(express.static(path.join(dirname, "client")))

**Comment by drozzy** [comment]
P.S.: Here is how I fixed the express issue:

    s = express["static"]
    app.use(s(path.join(dirname, "client")))

**Comment by haskellcamargo** [comment]
This happens because there are two ways to access object properties natively in JavaScript. You can either use `obj.prop` or `obj[prop]`, by index. The LiveScript compiler takes `static` as a reserved keyword and stores it as a string in form of an index acessor.

Either
```
s = express["static"]
app.use(s(path.join(dirname, "client")))
```
or
```
app.use(express["static"](path.join(dirname, "client")))
```
should have the same effect:
![static](https://cloud.githubusercontent.com/assets/7553006/7646948/4b9e05b0-faa2-11e4-943a-1f79c76dbe4b.png)

JavaScript has a good support for first class functions, therefore, static can be a HOF.
![static](https://cloud.githubusercontent.com/assets/7553006/7646966/98f49180-faa2-11e4-9b0e-9675d79d2199.png)

**Comment by drozzy** [comment]
I'm sorry, I still don't understand :-(
Is it a keyword in LiveScript language? Or in JavaScript?

If the former, is it documented somewhere? I've tried looking in the docs:
http://livescript.net/

and there is no mention f it.

**Comment by zloirock** [comment]
@drozzy it's reserved keyword in js and can't be used as property names in ES3 browsers.

**Comment by raine** [comment]
Why doesn't `app.use(express['static'](path.join(dirname, "client")))` work?

**Comment by drozzy** [comment]
@raine Good question. No idea... I'll try to investigate if I have time.

**Comment by drozzy** [comment]
@zloirock But is it a reserved in, say, a node.js application? Seems rather weird for "express" framework to be using it if it's reserved.

**Comment by zloirock** [comment]
@drozzy it's full equal. More weird to ask such questions.

**Comment by robotlolita** [comment]
@drozzy It's reserved everywhere in ES3, and it's allowed in member access positions in ES5.

In any case, `a.b` and `a['b']` are the same thing in JS. JS doesn't differentiate between these accesses like Python or Ruby do.

**Comment by determin1st** [comment]
it's 2018.. and it looks ugly in the JS source :(
