### ISSUE TITLE
Livescript AST

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#800]
Hi. It is possible to transform Livescript code into AST

Is it possible to transform AST back to Livescript code?

```
I would like to create a tool which transforms camelCase in snake-case
```

**Comment by robotlolita** [comment]
Yes, you can get an AST with `lsc --ast --json the-file.ls`, however that won't include every information in the source file, only the semantically significant nodes. That means that, if you generate LiveScript code back from that AST you'll lose non-meaningful data like comments, formatting, etc:

```
$ echo 'a   =  1 # foo' | ./node_modules/.bin/lsc -aj
{
  "type": "Block",
  "lines": [
    {
      "type": "Assign",
      "left": {
        "type": "Var",
        "value": "a",
        "first_line": 1,
        "first_column": 0,
        "last_line": 1,
        "last_column": 4,
        "line": 1,
        "column": 0
      },
      "op": "=",
      "opLoc": "=",
      "right": {
        "type": "Literal",
        "value": "1",
        "first_line": 1,
        "first_column": 7,
        "last_line": 2,
        "last_column": 0,
        "line": 1,
        "column": 7
      },
      "first_line": 1,
      "first_column": 0,
      "last_line": 2,
      "last_column": 0,
      "line": 1,
      "column": 0
    }
  ],
  "first_line": 1,
  "first_column": 0,
  "last_line": 2,
  "last_column": 0,
  "line": 1,
  "column": 0
}
```

If you need to preserve formatting, you'd need to write your own parser that gives you back a CST instead of an AST.

**Comment by heavyk** [comment]
I actually can think of a few times were I would have liked to transform my ls code... this would be a useful feature, imo.

I understand that things such as comments and potentially strange formatting would be lost, but it would be kinda neat to be able to globally transform my ls code like that. for example, when I started writing ls, I often times typed "return x" when I didn't need to. sure, I could search the code for all "return " and replace with '' but that would break any early returns I have. also, I used a lot-of-these-variables when now I would probably write them as snake_case_variables simply because they're a lot easier to read.

actually the problem doesn't seem too difficult to write an AST -> LS formatter. it'd be like compile but instead of to js, it'd be to ls. though, I can see some potential difficulties and comments would need to be added (preferably to the metadata on the nodes and not as new nodes - so relevant comments stay with its code). an easy test would be to transform lsc's ast back into ls (eg. source files should look like output files)...

I'll give it some more thought. it could be a lot more non-trivial than I imagine it to be right now...

**Comment by vendethiel** [comment]
This would mean a total rewrite of the LS lexer, so not really viable at the moment.

**Comment by waynedpj** [comment]
would something like this help make LS support possible with the very cool [grasp](http://www.graspjs.com)?

**Comment by heavyk** [comment]
why would it require a rewrite of the lexer? I would implement it in ast.ls where each ast class has a `compile: (o) -> ...` I'd just add a `compile-ls: (o) -> ...` - which in some cases would do nearly the same thing as the normal compile function, but it'd obviously be more complex to handle all the ls formatting - but still very doable.

**Comment by robotlolita** [comment]
@heavyk because currently LiveScript discards most of the useless information from the AST, like whitespace and comments.

**Comment by vendethiel** [comment]
Worse than that, the lexer does an insane amount of things, like adding implicit braces and parens or (yeah, it's in the lexer) expand `[1 to 50]`-style ranges

**Comment by robotlolita** [comment]
@vendethiel Ah, that's... yeah.

**Comment by heavyk** [comment]
oh, I see... well, yeah... I may still try it and end up rewriting the lexer in the process then. thanks for the tip :+1: the thing is, if I could do source transformations on LS, I'd use it for everything...

gonna think on it some more
