### ISSUE TITLE
choose your own syntax rules

### ISSUE THREAD

**Issue by thurt** [gkz/LiveScript#888]
I would like to slowly transition into livescript by selectively "turning on" certain rules. Could this be possible with livescript or some other tool? How might I get started down this path? Thanks!

**Comment by vendethiel** [comment]
That's far, far, far too complex. Just look at the lexer's complexity. It's insane.

**Comment by robotlolita** [comment]
Instead of "turning on certain rules" you could have a layered language (like Racket and Oz). But that would require LiveScript to be completely redesigned, from scratch.

A middleground would be implementing layers as macros (see Racket again, but also Dylan), but again, LiveScript's syntax is far too complicated for macros to work well.

In either case, you're way better off just designing your own minimal language and building optional features on top of that by using macros or something, really. It's going to be a ton less work.

**Comment by vendethiel** [comment]
And sweetjs is not nearly ready to use whitespace-sensitive readtables...

**Comment by rightfold** [comment]
You can pass string literals to the LiveScript compiler.

Or put your LiveScript and ECMAScript code in different files.

**Comment by thurt** [comment]
@vendethiel @robotlolita thanks for the ideas
No parentheses for function calls was my primary interest

**Comment by JoyKrishnaMondal** [comment]
just curious as to why livescript doesn't have macros - wouldn't it make it easier for people like @thurt  to write their own extensions as they please ?

**Comment by robotlolita** [comment]
We've discussed this at least a few times before (see https://github.com/gkz/LiveScript/issues/328), but no one has seriously worked on it afaik. Adding macros to the existing LiveScript compiler would be kind of impossible, writing a new compiler for it from scratch, that includes macros, is a lot of work given LiveScript's super flexible syntax, and the fact that LiveScript doesn't have a formal grammar or semantics (there's a lot of semantic work being done in the lexer :'D) makes it even harder, at least if you're looking to make it have the same semantics as existing LS :)
