### ISSUE TITLE
interesting output in two spots on the website (comprehensions)

### ISSUE THREAD

**Issue by falafflepotatoe** [gkz/LiveScript#944]
Not sure what to make of this.... was debugging on the playground and got some off the wall comprehensions... ex `[[1 2][3 4]]` doesnt work unless you use commas.

(disclaimer first day using LS)

    bar [[1 2][3 4]]
    // =>bar ([[(ref$ = [1, 2])[3], ref$[4]]]);
    // (obviously thats not a 2d array), expected: [[1,2],[3,4]]

    colmap = (fn,arr) -> 
	results = []
	for row,x in values arr
		for col,y in values row
			print "#x,#y #col"
			results.push(fn(col,y))
	results
        // doesnt work... here #col prints as undefined

       // the comprehension doesnt work also (tbh not sure this is right syntax thats what started the mess)
       arr = [[1,2],[3,4]]
       [col for col in row for row in arr]
       // => undefined has no properties

       // similarily even a simple loop doesnt work
       for row in [[1 2][3 4]]
         for col in row
           alert col
       // => Run error: missing ; before statement

Again this is on the website. not from command line.

**Comment by rhendric** [comment]
Hi @falafflepotatoe, welcome to LiveScript!

In your first example, you're seeing a feature called slicing ([documented here](http://livescript.net/#property-access)) wherein an expression like `anything[k1, k2, k3]` will get interpreted as `[anything[k1], anything[k2], anything[k3]]` (approximately—you can see that `anything` actually gets cached rather than duplicated). If you want an array of arrays, add a space (or comma, as you did later) between the inner arrays so it doesn't look like a slice.

In your comprehension example, you need to switch the order of the two `for` clauses; LiveScript will treat the first clause as the outermost loop. A little nonstandard, I know, but this way is consistent between comprehensions and non-comprehension nested loops, which behave similarly in LiveScript in most other ways as well. For example, you can treat a loop as a value in LiveScript, and it will be interpreted as a list of the values of the body of the loop, much like a list comprehension. (The biggest difference is that nested loops don't flatten the way nested list comprehensions do.)

**Comment by falafflepotatoe** [comment]
Ok that makes sense! thanks mucho!
