### ISSUE TITLE
Block-scoped variables

### ISSUE THREAD

**Issue by KSXGitHub** [gkz/LiveScript#962]
For example:

```livescript
test = 'foo'
console.log test # expect: foo

if true
   test = 'bar'
   console.log test # expect: bar

console.log test # expect: foo

**Comment by determin1st** [comment]
JavaScript has a function scope by default. It is very useful. So "expect"ation is not correct.

**Comment by KSXGitHub** [comment]
@determin1st 

1. JavaScript `var` keyword is function-scope, but `let` and `const` is block-scope

2. I am aware that LiveScript cannot enforce `var` to be block-scope. Hence, I suggest:

 * By default, LiveScript is compatible with old JavaScript standard, so it cannot use `let` and `const`, instead, it should rename block-scoped variables.

* If user tell LiveScript to not worry about old JS standard, but to worry about es6 only, `let` and `const` can be used.

**Comment by determin1st** [comment]
can you make an example, where block scope has practical superiority over function scope? i never encounter such a situation.

**Comment by KSXGitHub** [comment]
@determin1st I should ask you an example where local variable has practical superiority over global variables then? Because everything just fine being global, why implement scope/context at all!

ES6 implements `let` and `const` to make block-scope possible, and it do it for a reason: The JavaScript comunity demand it, and they also demand it for reasons.

**Comment by determin1st** [comment]
@KSXGitHub 

yes, but it's not an example) it doesnt matter what crowd says until me see the benefits.
function scope is not global scope, so if there is a need to reduce scope, no problem to add a function inside. JavaScript is not class-typed-imperative language, it's prototypal-ducktyped-functional style.

ES6 let/const/class may give something, but i cant see what (practical application).

**Comment by KSXGitHub** [comment]
@determin1st I could add a function inside and call it immediately, the problem is, it's ugly. For instance, I could add a `do ->` which then transform into JS `(function () { ... })()`. In JS, I have no problem writing that extra `(function () {` and `})()`. In LiveScript however, I have to add one extra line for `do ->` and one extra level of indent.

**Comment by determin1st** [comment]
@KSXGitHub 

lot of things may be solved using both functions and fors. You say, that

a.forEach (el, index) !->
  # some code

or

for el,index in a
  # some code

is uglier than

a.forEach(function(el, index) {
  # some code
});

or

for (let index=0; index < a.length; index++) {
  el = a[index];
  # some code
}

okay, why not using new JS/ES? Personally, i dont like LS *for* with integer loop [implicit from 0], because it doesnt allow to reuse a variable. anyway im not skilled to make changes to LS yet. just bring some examples)

**Comment by KSXGitHub** [comment]
@determin1st You're right about iteration/loop, the JS version is definitely uglier. But no, I'm not talking about iteration/loop. I'm talking about what I was talking about - **scope** - that `/* some code */`. I want to declare a block-scoped local variable without affecting the whole function-scope.

```livescript
if con1
  var1 = 123
  console.log var1 # expect: 123

  if con2
    var2 = 456
    console.log var2 # expect: 456

  console.log var2 # expect an error, var2 is not defined in this block-scope

console.log var1 # expect another error, same reason

**Comment by determin1st** [comment]
```
a = !->
    if con1
        var1 = 123
        console.log var1
    if con2
        var2 = 456
        console.log var2

b = !->
    console.log var2 # as expected
    console.log var1 # same problem

a! and b!
```

**Comment by KSXGitHub** [comment]
@determin1st 

1. It's not just `if con1` and `if con2`, it's `if con1` and `if con1 and con2`. Also, `con1` and `con2` may not be variables but expressions.

2. Note that although the global context cannot access to both `var1` and `var2`, the `if con2` still able to use `var1` from parent scope while the `if con1` one cannot access `var2`. Your "refactored" code can't do that.

3. Even if I only want to do what you assumed (in the code you shown), the code is not straightforward.

**Comment by determin1st** [comment]
@KSXGitHub 
yes, it was straightforward, that's why i ask for a practical example. it may show the power of block-scope or may fall by rewrite.. now, i agree, that this rewrite is uglier - but it does what is expected)

**Comment by rhendric** [comment]
@KSXGitHub, are you aware of LiveScript's existing `let` keyword?
```ls
test = 'foo'
console.log test # out: foo

if true
    let test = 'bar'
        # Note the indentation; unlike EcmaScript let, which uses the enclosing
        # block scope, LiveScript let creates a new scope inside which the
        # variable is defined. You can define multiple variables in a single let;
        # no need for multiple nested blocks.
        console.log test # out: bar

console.log test # out: foo
```

**Comment by KSXGitHub** [comment]
@racklin 

![image](https://cloud.githubusercontent.com/assets/11488886/25717267/225d0cb0-312c-11e7-95bc-f8d01e455517.png)

**Comment by ozra** [comment]
There's no limit to how small a scope one would want a var confined to. The smaller the better! Saying "function level is good enough for everyone" is like saying "640kB ought to be...".

there should be a keyword.

**Comment by ozra** [comment]
Oh, new comments already. Yeah, ls `let` is goofy.

**Comment by ozra** [comment]
it _should_ use the enclosing scope.

**Comment by KSXGitHub** [comment]
@rhendric Thank for telling me this, I wasn't aware of it. Still, I don't want to *add one extra level of indent* - the very reason I don't just use `do ->` in the first place

**Comment by rhendric** [comment]
Okay, I'm going to take a quick look at how involved it would be to add a version of `let` that implicitly indents the remainder of the scope if it isn't followed by an indented block. Will report back.

**Comment by KSXGitHub** [comment]
@rhendric I don't think reusing keyword `let` is a good idea

**Comment by rhendric** [comment]
Adding a new keyword to the language is probably a no-go for a feature this minor, to be honest. What are your issues with `let` serving both duties?

**Comment by KSXGitHub** [comment]
I'm afraid it would lead to confusion, but if you can distinguish two usages of `let`, just go with it :smile: 

```livescript
if true
  let foo = 123
  console.log foo # no problems

  let bar = 456
    console.log bar # no problems

  console.log bar # expect an error here
```

**Comment by KSXGitHub** [comment]
I think `const` should be block-scope as well as `let` (just like const/let in JS).

```livescript
# This is a constant variable, let's call it foo(1)
const foo = 12
console.log foo # expect 12

if true
  # Currently, this is considered a re-definition of foo(1)
  # which is, of course, forbidden
  # But obviously, no one would want to re-define a constant
  # instead, this should be a completely different constant, let's call it foo(2)
  const foo = 34
  console.log foo # expect 34

  # We should also be able to do this, just like we do with `let`
  # The following constant is only available in the following "sub-scope"
  # Let's call it foo(3)
  const foo = 56
    console.log foo # expect 56

  console.log foo # expect 34, this is foo(2)

console.log foo # expect 12, this is foo(1)
```

**Comment by determin1st** [comment]
```
var1 = 123 if con1
var2 = 456 if con1 and con2

console.log if var1 then var1 else 'error expected'
console.log if var2 then var2 else 'error expected'
```

**Comment by rhendric** [comment]
Okay, good news first: the thing I proposed is fairly easy to implement.

Now for the slightly troubling news. LiveScript `let` has a couple of extra quirks up its sleeve relative to ECMAScript `let`. First, in ES, `let foo` by itself means to declare a block-scoped variable `foo` without a value yet. However, in LiveScript, `let foo` basically means `let foo = foo`; it takes the current value of `foo` from an outer scope and uses it as the initial value of `foo` in a new scope. Second, in ES, `let b = a, c = b` will ultimately set `c` equal to the value of `a`; the definitions execute sequentially. In LS, `let b = a, c = b` means something different: the definitions all run simultaneously, so `c` will take the value `b` had in the parent scope, not necessarily the value of `a`. For these reasons, achieving both ‘LiveScript block `let` works the same as LiveScript bodyless `let`’ and ‘LiveScript bodyless `let` works the same as ECMAScript `let`’ won't be possible.

I think consistency within the language is more important than consistency with similar ECMAScript features, so I propose keeping both of the above quirks for bodyless `let`. To achieve sequential definitions, as with ES `let b = a, c = b`, the correct LiveScript can be `let b = a; c = b` (which is similar to how one-line regular variables definitions in LiveScript have to be written `b = a; c = b`; a comma is no good there). To achieve declarations without definitions, a new feature can be added to both block and bodyless `let`: the form `let var a, b` will declare `a` and `b` in the child (if block) or remainder of the current (if bodyless) scope, exactly as if `var a, b` were moved to the first line of that scope.

This last form also suggests a way to address `const` as well, by permitting a similar `let const` form. Rewriting your example as
```ls
# This is a constant variable, let's call it foo(1)
const foo = 12
console.log foo # expect 12

if true
  # Currently, this is considered a re-definition of foo(1)
  # which is, of course, forbidden
  # But obviously, no one would want to re-define a constant
  # instead, this should be a completely different constant, let's call it foo(2)
  let const foo = 34
  console.log foo # expect 34

  # We should also be able to do this, just like we do with `let`
  # The following constant is only available in the following "sub-scope"
  # Let's call it foo(3)
  let const foo = 56
    console.log foo # expect 56

  console.log foo # expect 34, this is foo(2)

console.log foo # expect 12, this is foo(1)
```
works with my current experiments.

How do we feel about all this?

**Comment by KSXGitHub** [comment]
@rhendric I was never aware of such behaviour in JavaScript, this worth noticing. I want only block-scope variables, so I'm fine either way.

**Comment by ozra** [comment]
Agree; consistent quirks are better than inconsistencies.

**Comment by rhendric** [comment]
@KSXGitHub, you can clone [my bodyless-let branch](/rhendric/LiveScript/tree/bodyless-let) to try the syntax out. Let me know if you have any issues with how it works.

**Comment by KSXGitHub** [comment]
@rhendric Thanks! It works well with keyword `let`.

**Comment by KSXGitHub** [comment]
@rhendric Only there is one problem:

```livescript
let const foo = 123
console.log foo

let const foo = 456 # Expect an error here, should it be forbidden?
console.log foo

**Comment by rhendric** [comment]
That's as intended. Original LiveScript `let` always creates a new scope, and so these new variations do as well. (You may want to be economical with your `let`s with this in mind; one per block is probably enough even if you're defining variables several times in that block.) The above is really just shorthand for this:
```ls
let
  const foo = 123
  console.log foo

  let
    const foo = 456
    console.log foo
```

**Comment by KSXGitHub** [comment]
@rhendric So, `let const` makes sense! I was expecting to use `let` in LiveScript the I use it in JavaScript (a replacement of `var`) without realizing that `let` in LiveScript was never meant to be a variable declaration, but rather, a scope declaration.

You really should write some comparison between LiveScript and JavaScript (and other common languages) in the [Wiki](https://github.com/gkz/LiveScript/wiki) or the [Official Website](http://livescript.net/) to avoid confusion.

**Comment by rhendric** [comment]
Here's another potential gotcha for you, which just occurred to me:
```ls
a = 1
if true
  a = a + a
console.log a # => 2

a = 1
if true
  let b = a + a
  a = b
console.log a # => 1 (!)
```
I'm concerned, especially based on the above conversation, that people would be very surprised when they see that this doesn't output 2 both times. The key, again, is understanding that `let` always creates a new scope, and that `:=` is necessary if you want to mutate a variable in an outer scope. But since this new form of `let` doesn't use indentation to indicate the new scope, it's less obvious what's going on; looks like referential transparency is being broken.

The situation is similar with backcall syntax:
```ls
a = 1
if true
  a = 2
  <- (.call!)
  a = 3
console.log a # => 2
```
Although with backcalls, the `<-` may be more suggestive of scope shenanigans than `let` is.

I'm starting to wonder whether saving you from having to indent a block is worth the headache of having a syntax that looks like ES `let` but definitely isn't.

**Comment by KSXGitHub** [comment]
@rhendric OK. I think it's not worth it. However, I think you should create every JavaScript function for each LiveScript block-scope.

### Example

```livescript
if true
  foo = 123
  console.log foo
```

**Current behaviour**

```javascript
var foo;
if (true) {
  foo = 123;
  console.log(foo);
}
```

**Expected behaviour**

```javascript
var foo;
if (true) (function _block_scope() {
   foo = 123
   console.log(foo)
}).call(this)
```

### Another suggestion

Why don't compile LiveScript to ES7 syntax, then, use [babeljs](https://babeljs.io/) to create ES5-compatible code. If you do this, it would be way easier to implement/integrate ES6/ES7

**Comment by caasi** [comment]
> Why don't compile LiveScript to ES7 syntax, then, use babeljs to generate ES5-compatible code. If you do this, it would be way easier to implement/integrate ES6/ES7

You may like to check https://github.com/gkz/LiveScript/issues/821 and https://github.com/dk00/livescript-next.

**Comment by rhendric** [comment]
Making every block its own scope would be an even bigger change (existing code would have to change a lot of `=`s to `:=`s, and I imagine there would be performance concerns as well), and is definitely off the table for original flavor LiveScript.

For new and exciting flavors of LiveScript, the two links in caasi's comment are good places to start, although I think even livescript-next is trying to be backwards compatible. You could also try floating your thoughts on https://github.com/livescript/discuss, and maybe you and/or some of us there can get started on a successor language that incorporates your ideas.

**Comment by igl** [comment]
We should have `const` but no block scope. Function scope is great.

> ES6 implements let and const to make block-scope possible, and it do it for a reason: The JavaScript comunity demand it, and they also demand it for reasons.

ah... reasons! Putting the java back in javascript?

**Comment by vendethiel** [comment]
> ah... reasons! Putting the java back in javascript?

That comment doesn't make sense.

There are some very compelling use cases, one of them being `for (let)` (which we have in LS).

**Comment by KSXGitHub** [comment]
@igl 

> Function scope is great.

You mean scope is great? Because function scope is the least/basic requirement of scope.

> but not block scope

What's wrong with block-scopes? What can function-scope do but block-scope cannot?

**Comment by igl** [comment]
My main es6 frustrations around block scope are these imperative-styled one-time assignments:

```
let result
try { result = ... 
```

LS does not have that problem because everything is an expression.

So what does block scope bring to the table in LS? More imperative code like `for (let)`?
Let's face it: we only use fugly for-loops because we are paranoid about perf and we probably never get TCOs in v8

**Comment by KSXGitHub** [comment]
@igl 

> ```
> let result
> try { result = ...

I'm confused. You could use `var` in place of `let` here, and `var` is function scope. Does scopes have anything to do with this? I thought let vs const has nothing to do with function-scope vs block-scope.

**Comment by robotlolita** [comment]
@igl v8 has been shipping with PTC for about a year now. Though I don't know if it does unrolling for tail recursive functions like it does with loop bodies.

In any case, "block" scoping (to the extent you can call an expression a 'block') is something every functional programming language implements:

```ml
let x = 1
in let x = x + 1
in let x = x + 1
in display x  (* => 3 *)
```

Is just block scoping. And it's a very useful way of naming expressions inside of a function without having one name interfere with another name. The major difference between that and what JS does is that `let` creates a new scope, rather than modifying the current block's scope.

**Comment by determin1st** [comment]
@igl,

1. you dont have to prove anything, because (https://en.wikipedia.org/wiki/Russell%27s_teapot ) the burden is on those who state.

2. let them use block scope) periodicly, i check what ppl do with their programming skill and see lack of function and much of style and form.

3. let them fall into compile/build/tool/scope/names control. and just control state of your programs. time and work will show what is more effective. i see what D.Crockford is doing and what he says now, it's a change, but it's a change to moneymaking.

**Comment by KSXGitHub** [comment]
@determin1st I can see your devotion to declarative programming paradigm (especially functional paradigm) and your hatred towards imperative one and everything related to it (including block-scope). The thing is, scopes have absolutely nothing to do with these paradigms. Programming is a practical job, a part of science, not a religion. GitHub is a place for people to exchange ideas, not for flame wars.

**Comment by igl** [comment]
Yea, i don't mean to be mean spirited either.
In retrospect i think i should have written my earlier posts lighter. Written text often does not communicate spirit well. 

@robotlolita made some valid points i agree with. Specially when thinking about expressions as blocks.

My main beef is with JS (not LS) not having if/for/try as expressions (that would solve my problem of wanting `const`, but forced to use `var/let`)
It's a puny addition to JS and I really don't see the big benefit.

I just scanned my lasts project code and i never ever write functions longer than 20 lines with (1-2 exceptions) and "reducing the amount of code you need to scan" isn't really a problem for me that scope rules would change.

I am also quite accustomed to function scope after writing JS for 15 years :)

**Comment by determin1st** [comment]
@KSXGitHub 

sure, i have hatered and emotions, because im alive (yet). you dont? i cant belive i would write anything without personal itch and i would be able to step over what i used to like without hatered. if you can, then you are super-human)

all science is based on that. the problems and solutions. so i will try (as i posted in other issue) to build ui library using LS. if you can help me with anything (links to nice ui-techs, controls/widgets, ppl who do the same job and what you find useful) lets cooperate. block-scope is just block-scope, im not against you using it. i just dont use it myself.

**Comment by KSXGitHub** [comment]
> im not against you using it. i just dont use it myself.

You contradict yourself: If you were not against anyone using it, why express such emotion? For what I know, supporting block-scope does not prevent you from doing functional programming.

You can choose not to use it! If you want people to follow your rules when contribute to your project, you can enforce it (which, I always do! With tools! Such as [standard](https://github.com/feross/standard)!).

**Comment by determin1st** [comment]
@KSXGitHub 

yes, it doesnt prevent functional style, it prevents variable reuse and creates var flood. it may affect (more code) closures, nested and long functions if you strictly follow the rule not to reuse vars. but it's about the style not the exit function of your code.

no, i will use and (re)use it. ;) and will never enforce anyone who may give useful synced functionality. see, when we use libs like jQuery, GSAP and others, we dont go to their devs and say, hey, im going to write something, change your code style to conform my project, but we do it when we are on the top (project lead). it's not good for cooperation. lets anyone have his/her own evironment, because the real utopia (is what Crockford says), i believe, is to have this absolute equal tools and style for all.

for example, i often do a long functions (bad practice?) in a big file (if you look at ui libs, it's common) and have no problem because i use markers (in vim editor) to navigate through code. today, ppl use atom or VS and have a small code map where they navigate with the mouse, or jump to code with search. it limits the size of file (because of long scroll and name collisions). they split this code to files which are also a navigation markers and use build tools. so it's a complex problem to force one to "dont use atom" == "use vim". use what you used to and make it work with the rest and be tested, that's a true requirement.

im new to github. came and rewrote a jquery-ui slider widget (here: https://codepen.io/determin1st/pen/zZPBbY). it was based on old code. lead looked into code and said "we dont need to rewrite it". he looked at it's code style, not at the exit function. okay. i fixed a bunch of bugs (here is a testcase: https://codepen.io/determin1st/pen/RVxKEJ ). he looked in code and said "we dont need it" again - he didnt like the style (var names, spaces, tabs, etc). how do they plan to evolve? i dont know) it's not a paid job, right?

that's why, i dont belive (no religion) in style unity. person should plan (copy) a widget/control and code it in separate file (or in main if he is a vimmer) with help of jQuery/UI-Lib Core/GSAP or other not obligatory helpers in his own evironment, test it, make an example - that's all. commit if it works. to promote LS, syntax should be in LS.

this text is not related with block-scope, so, sorry if it hurts)

**Comment by KSXGitHub** [comment]
@determin1st 

Before we discuss any further, I feel like this conversation is completely irrelevant to the issue, it's not even relevant to LiveScript itself. Can we get back on track please?

-----------------

> when we use libs like jQuery, GSAP and others, we dont go to their devs and say, hey, im going to write something, change your code style to conform my project

Of course we don't, I always consider the libs as dependencies, not part of the project, even when I copy them to my repo. Therefore, the rules apply to the libs is only for their place inside project if not in `package.json`. The only thing I do with these libs are including, excluding, updating version. I never make changes to their code inside my project. However, when you're contributing to, say React for instance, you must follows their rules, otherwise CI tests would fail and no one would care about your pull request (you know, people love CI, 'cause time is precious).

> it's not good for cooperation. lets anyone have his/her own evironment

No, it's just not beginner-friendly! If there're no rules, the project would turn into a complete mess. Everyone hates mess above all else (for instance: I am completely OK with either spaces or tabs, but not OK with mixing them together). When your project turns into an utter mess, the only thing that you can do is rewrite it from scratch.

> the real utopia (is what Crockford says), i believe, is to have this absolute equal tools and style for all.

No one rules out the editor you use nor the development environment you're in but some rules (it's rules, like design principles, not laws; but "rules" as I mention) must be established: How to build your project, how to test it, how to deploy, etc. Any dev environment can ensure these rules is OK.

> he didnt like the style (var names, spaces, tabs, etc). how do they plan to evolve? i dont know)

IMHO, the cost of maintaining project outweighs the benefit of fixing a few minor bugs. In order for the project to evolve, the project must be maintainable first (I'm OK if the LiveScript devs decline this issue for maintaining reasons). The team lead would, of course, enforce whatever rules he/she likes, but rules is not for just decorating, it is here to ensure consistency. Rules are important. 

> it's not a paid job, right?

Well, in this case, _"Yes, I didn't ask you to contribute to my project, and you don't get paid for that, but do I get paid for spending time on reading your code? I did write a goddamn CONTRIBUTING.md which is mentioned in my README.md which is here even before you fork my repo. Could you please you RTFM?"_, or, if you want to be nicer, just put CI scripts there to politely ask people to follows some rules before even contribute to the projects. Wise ones always do that one way or another, for the reason above.

> that's why, i dont belive (no religion) in style unity

I have a better analogy: Let's say that there is no single worldwide law for everyone but each country has its own consistently laws for its citizens. The laws may be "good", may be "evil", may be strict, may be free, but one thing for certain: it is necessary in order to maintain a stable society.

> this text is not related with block-scope, so, sorry if it hurts)

In contrast, I believed that I hurt you.

**Comment by caasi** [comment]
@KSXGitHub

Why don't you fork LS or just create your own language?

**Comment by KSXGitHub** [comment]
@caasi Why do you me this question? I remember that I did not say "I'm gonna create my own" or anything like that. All I did here are: asking for block-scope, discuss with some guys I don't know about programming paradigms, go full philosophical about "rules". Your question is confusing me.

Now I answer your question: I can just fork LiveScript and create my own but why must I do that? LiveScript is here and it is fine so far. Although I opened this issue because I want block-scope in LiveScript, lacking it does not make LiveScript unusable. After all, block-scope is just nice to have.

**Comment by caasi** [comment]
I see. You are not enforcing anything.

**Comment by KSXGitHub** [comment]
@caasi Well, I'm not LiveScript author, I don't enforce its rules.

**Comment by determin1st** [comment]
@KSXGitHub 

well, in fact, LS reduces count of the rules of JS - it's good. block-scope is a new feature, so it might be added but the problem is how. if you spirited enough, you could start looking through it's code and find a solution which doesnt affect others or help mr. @rhendric 8) to do the job.

**Comment by rhendric** [comment]
More people contributing to LiveScript would certainly be welcome! But in the case of this particular request, the issue is with the design, not doing the work. `let` and `const` are already tied to function scope in LiveScript, in ways that users may be depending upon. Unlike the situation with `await`, for example, I don't think the advantages of block-scoped variables justify introducing a new keyword, which is also a form of backward-incompatible change. And as examples upthread have demonstrated, using function scope `let` to approximate the syntax of block scope `let` looks like it will lead to either confusion (if existing function scope semantics are kept) or internal language inconsistency (if `let` gets two different meanings). Since we can't create something new, and we can't reuse something old, I don't think this feature can be delivered.

Feel free to reopen if you see any holes in this analysis, but I don't think there's any way around it.
